Fix #4227: Add specialized versions of j.u.function.Consumer
scala-js/scala-js pull request #4241
Opened 2020-10-10 16:51 UTC by er1c

I *think* I got all of the formatting correct this time 🤞

2020-10-24 19:18 UTC, er1c commented
@sjrd or @gzm0 any issues here I need to address?

2020-10-24 19:27 UTC, sjrd commented
I haven't found the time to look at this one yet, sorry. I will try and find some time this week.

2020-10-24 19:28 UTC, er1c commented
@sjrd no problem!

2020-11-01 02:39 UTC, er1c commented
@sjrd ping as a friendly reminder, no rush

2020-11-09 16:47 UTC, sjrd requested changes
Sorry for the long delay.

The implementation looks good. I just find the tests of `ObjXConsumer` too complicated for what they're testing. See below.

2020-11-09 16:47 UTC, sjrd commented on test-suite/shared/src/test/scala/org/scalajs/testsuite/javalib/util/function/ObjDoubleConsumerTest.scala
> +    }
That is a fairly complicated test, which involves a number of moving parts that are unrelated to `ObjDoubleConsumer`: `java.util.List`, its `forEach` method, the generic `Consumer[T]`.

Consider a test where the `ObjDoubleConsumer` simply stores its two arguments in an enclosing `var result: (SomeClass, Double)`. There's no need to involve the collections here.

(of course the same comment applies to the other `ObjXConsumerTest`s.

2021-03-27 16:45 UTC, tarsa commented
I think this PR was completely superseded by https://github.com/scala-js/scala-js/pull/4365

2021-03-27 16:50 UTC, sjrd commented
Oh, indeed.

2021-03-27 16:50 UTC, closed without merging