Enable and test j.u.Objects#requireNonNull with message Supplier argument
scala-js/scala-js pull request #4259
Opened 2020-10-18 21:38 UTC by LeeTibbert

Recent work porting Scala.js j.u.Objects to Scala Native made me aware
of the commented out requireNonNull method at the bottom of the file.
That method uses a message Supplier.

Scala Native has had j.u.f.Supplier for a while. Recent work by
Eric Peters (at_er1c) recently added that class for Scala.js. The comment
was correct for the past 5 years or so but is now disinformation.

This PR enables the commented out code. This yields completeness and
eliminates an obsolete comment.

2020-10-19 11:48 UTC, sjrd requested changes
The commit message can be shortened to remove "personal" aspects from it. We tend to keep them factual and not relate to personal stories like motivation, history and goals. We can reference issue numbers or past commit shas. When we need a pronoun, we use "we". So perhaps here it could be:

    Enable j.u.Objects#requireNonNull with message Supplier argument

    Now that we have j.u.f.Supplier, the comment had become obsolete.
    We can now implement that method.

2020-10-19 11:48 UTC, sjrd commented on javalib/src/main/scala/java/util/Objects.scala
> +     else obj
```suggestion
  def requireNonNull[T](obj: T, messageSupplier: Supplier[String]): T =
    if (obj == null) throw new NullPointerException(messageSupplier.get())
    else obj
```

2020-10-19 11:48 UTC, sjrd commented on test-suite/shared/src/test/scala/org/scalajs/testsuite/javalib/util/ObjectsTest.scala
> +      }
A bunch of whitespace fixes:
```suggestion
    val message = "All is well!"

    val successSupplier = new ju.function.Supplier[String] {
      def get(): String = message
    }

    val failureSupplier = new ju.function.Supplier[String] {
      def get(): String = {
        throw new AssertionError(
            "Objects.requireNonNull() should not have called Supplier")
      }
    }
```

2020-10-19 11:48 UTC, sjrd commented on test-suite/shared/src/test/scala/org/scalajs/testsuite/javalib/util/ObjectsTest.scala
> +      case e: NullPointerException => assertEquals(message, e.getMessage())
I believe you were looking for `AssertThrows.expectThrows`, to assert that an exception is thrown, and additionally get the instance to check its message in a subsequent `assertEquals`.

2020-10-20 21:59 UTC, LeeTibbert commented
Changed as requested.  Thank you for the suggestions and concrete examples, especially for the commit message. AssertThrows.expectThrows was new to me and sure cuts down the code and makes it more readable.

2020-10-21 07:07 UTC, sjrd approved these changes

2020-10-22 15:26 UTC, merged