Fix #4311: Do not move input files in HTMLRunnerBuilder
scala-js/scala-js pull request #4314
Opened 2020-12-04 14:03 UTC by gzm0

It is unclear to me why I thought this is necessary in the first
place.

We leave the scalaJSTestHTMLArtifactDirectory key/settings in place
since they do not hurt and removing will break compatibility.

Further, we add a section to TESTING to test ES module support in the
browser (the full testSuite is not in there yet, due to #4312).

2020-12-04 14:18 UTC, sjrd requested changes
It was probably necessary for `Input`s whose `Path`s do not refer to the real file system (like a `Jimfs` for example).

We may still want to perform a copy for such `Path`s (while avoiding the copy for real files).

2020-12-04 14:18 UTC, sjrd commented on TESTING
> +> set scalaJSLinkerConfig in testingExample.v2_12 ~= (_.withModuleKind(ModuleKind.ESModule))
```suggestion
> set scalaJSLinkerConfig in testingExample.v2_12 ~= (_.withOutputPatterns(OutputPatterns.fromJSFile("%s.mjs")).withModuleSplitStyle(ModuleSplitStyle.SmallestModules).withModuleKind(ModuleKind.ESModule))
```
It's a long line, but it avoids reloading the sbt build twice for nothing.

2020-12-04 16:54 UTC, gzm0 commented
Yeah, good point. I have amended most of changes and simply added copy avoidance. I have also added a test for these use cases, so next time the test suite will just yell at me automatically :P

2020-12-05 17:05 UTC, sjrd approved these changes

2020-12-05 17:06 UTC, merged