Change Matcher#replace* behavior to match JVM
scala-js/scala-js pull request #4356
Opened 2020-12-29 20:43 UTC by nightscape

This is a minimal PR to make the behavior of `Matcher#replace*` methods behave like their JVM counterpart by not appending the String `"null"` when a match group is `null`.
Fixes https://github.com/scala-js/scala-js/issues/4350.

2021-01-04 09:40 UTC, sjrd requested changes
Thank you for the PR. The code and test look good. I only have one formatting comment below. Also, to match [our commit message guidelines](https://github.com/scala-js/scala-js/blob/master/CONTRIBUTING.md#creating-commits-and-writing-commit-messages), the issue number should be in the title. The title could also be a bit more precise in what it changes exactly. Perhaps consider

    Fix #4350: Handle non-matching groups in Matcher#replace*.

2021-01-04 09:40 UTC, sjrd commented on javalib/src/main/scala/java/util/regex/Matcher.scala
> +          if (replaced != null) sb.append(replaced)
According to our coding style, side-effecting branches of an if must always be on their own line:
```suggestion
          if (replaced != null)
            sb.append(replaced)
```

2021-01-04 22:17 UTC, nightscape commented
@sjrd I added your formatting suggestions and renamed the title of the commit and PR :+1:

2021-01-04 23:12 UTC, sjrd approved these changes
Thank you. LGTM!

2021-01-05 07:37 UTC, merged

2021-01-05 11:05 UTC, nightscape commented
@sjrd thanks for helping me get my first Scala-JS PR merged :smile: