Upgrade sbt to 1.3.13.
scala-js/scala-js pull request #4360
Opened 2021-01-06 13:38 UTC by sjrd

This is the latest (and very likely last) 1.3.x version.

Recent versions of Metals cannot import builds using sbt 1.2.x anymore. The initial import fails with a LinkageError because it wants to access a setting that was added in sbt 1.3.0.

This change may make our sbt plugin incompatible with sbt 1.2.x builds, as our main source of tests for it are our own build. However, almost all the scripted tests force to use sbt 1.2.8, and should give some confidence that we aren't breaking anything.

If we do, oh well, sbt 1.2.x is a bit old anyway.

2021-01-06 13:49 UTC, gzm0 requested changes

2021-01-06 13:49 UTC, gzm0 commented on project/Build.scala
> +      useSuperShell := false,
Isn't this something that should go in the personal/local sbt config?

2021-01-06 14:24 UTC, sjrd commented
Turning into draft because it seems that things are recompiled every time with that version.

2021-01-07 11:04 UTC, sjrd commented
Asking on sbt's gitter: https://gitter.im/sbt/sbt?at=5ff6e122787d8f79c8e86eba

2021-06-25 06:20 UTC, sjrd commented
Superseded by #4516.

2021-06-25 06:20 UTC, closed without merging