Fix #4465: Properly call default param getters for nested JS ctors
scala-js/scala-js pull request #4502
Opened 2021-06-06 12:37 UTC by gzm0

2021-06-07 09:41 UTC, sjrd requested changes

2021-06-07 09:41 UTC, sjrd commented on compiler/src/main/scala/org/scalajs/nscplugin/GenJSExports.scala
> +            genNew(trgSym, trgSym.primaryConstructor, captures)
I'm pretty sure this is incorrect. We could create several instances of the module per enclosing instance, if we use a `new` every time. We should use the *getter* method on the enclosing instance instead. If the enclosing instance is a JS class, that means accessing the property of its `JSName`; if it is a Scala class, it means calling the Scala method with its name and 0 argument.

2021-06-07 09:41 UTC, sjrd commented on compiler/src/main/scala/org/scalajs/nscplugin/GenJSExports.scala
> +            genNew(trgSym, trgSym.primaryConstructor, captures)
We should add a side-effect in the constructor of the companion object in the tests, and test that it is only applied once per enclosing instance.

2021-06-07 16:05 UTC, gzm0 commented
Uh oh, this sounds more complicated. Shall we postpone this past 1.6.0?

2021-06-07 19:32 UTC, sjrd commented
Yes, let's postpone it.

2021-07-11 08:25 UTC, sjrd requested changes
The fix basically LGTM now. I have a few minor comments.

2021-07-11 08:25 UTC, sjrd commented on compiler/src/main/scala/org/scalajs/nscplugin/GenJSCode.scala
> +      }
This comment still stands.

2021-07-11 08:25 UTC, sjrd commented on compiler/src/main/scala/org/scalajs/nscplugin/GenJSExports.scala
> +            assert(captures.isEmpty, "expected empty captures")
Isn't that assertion already covered by
```scala
assert(trgSym.isLifted == captures.nonEmpty,
```
a few lines above?

2021-07-11 08:25 UTC, sjrd commented on compiler/src/main/scala/org/scalajs/nscplugin/GenJSExports.scala
> +            val outer = enteringPhase(currentRun.picklerPhase)(trgSym.owner)
Does `trgSym.originalOwner` work? It doesn't require time travel, IIRC.

2021-07-11 08:25 UTC, sjrd commented on compiler/src/main/scala/org/scalajs/nscplugin/GenJSExports.scala
> +            val receiver = captures(0)
```suggestion
            val receiver = captures.head
```
?

2021-07-11 09:14 UTC, gzm0 commented on compiler/src/main/scala/org/scalajs/nscplugin/GenJSCode.scala
> +      }
I have also renamed `sym` to `ctorSym`. It was confusing me as well :P

2021-07-11 09:24 UTC, sjrd approved these changes

2021-07-11 16:48 UTC, merged