Add an ugly way to call `**`
scala-js/scala-js pull request #4619
Opened 2022-01-02 16:51 UTC by catap

One of the main benefits of `BigInt` is `**` for a large number and it is shame that Scala.JS can't do it out of the box.

Let me add it in an ugly way, but much better than as users to research the way to do it.

2022-01-02 16:55 UTC, sjrd requested changes
While we should definitely add a way to support `**`, we shouldn't use the ugly way in the standard library. We should do all the hard work of actually supporting it through the entire pipeline.

2022-01-02 20:05 UTC, catap commented
@sjrd this seems much more complicated. Honesly, I have no idea how to add `**` without adding such token to scala.

2022-01-03 00:41 UTC, gzm0 commented
@sjrd we should watch out for silent source breaking changes. IIRC `def **` would compile to bracket selecting `"**"` right now.

2022-01-03 06:34 UTC, sjrd commented
Yes, I know. This is the tricky part of adding this feature.

2022-01-30 10:21 UTC, gzm0 commented
> This is the tricky part of adding this feature.

I'd to the following:

- Introduce `JSOperator` (similar to `JSBracketAccess` / `JSBrackedCall`, maybe unary / binary).
- Warn on JS members with names that are not JS identifiers if they do not have `JSName`.

> Honesly, I have no idea how to add ** without adding such token to scala.

@catap in Scala, operators are not special. They are simply methods. `1 + 2` is simply `1.+(2)`. So you can simply define a `**` method, and `1 ** 2` will turn into `1.**(2)`. The tricky bit here is to teach the Scala.js compiler that it needs to translate `x.**(y)` into `x ** y` and not `x["**"](y)`.

2022-01-30 10:55 UTC, sjrd commented
Hum. An `@JSOperator` could solve the compatibility issue, indeed. I had not thought about that. 🤔

2022-08-31 08:26 UTC, sjrd commented
Closing for inactivity, but I opened #4719 to remind us that we need to find a solution.

2022-08-31 08:26 UTC, closed without merging

2022-08-31 09:49 UTC, catap commented
Indeed I forgot about this 😭