A better fround polyfill that uses no `Math.*` method.
scala-js/scala-js pull request #4638
Opened 2022-02-09 13:12 UTC by sjrd

We avoid calls to `Math.log` and `Math.pow`, along with several additional instructions, by using a clever application of Veltkampt's splitting algorithm.

In addition, we streamline the code paths for zero'es and NaN, and add an explicit conversion from `null` to `+0` to avoid any potential deoptimization.

2022-02-09 16:37 UTC, gzm0 requested changes
Only a nit :)

2022-02-09 16:39 UTC, gzm0 commented on linker/shared/src/main/scala/org/scalajs/linker/backend/emitter/CoreJSLib.scala
> +                // NaN, +0 and -0 fall in this case as well, and this computation is an identity for them
Just saw that: You might want to drop a comment that for the -0 case, neither `av` nor `absResult` are really absolute (as in: they end up being -0).

2022-02-09 16:56 UTC, sjrd commented
Updated.

2022-02-10 12:39 UTC, gzm0 approved these changes

2022-02-10 12:56 UTC, merged