Small javalib cleanups
scala-js/scala-js pull request #4666
Opened 2022-04-28 09:44 UTC by sjrd

2022-04-30 06:17 UTC, gzm0 requested changes
I only have higher level comments regarding the 3rd commit:

Just to clarify, is the goal here to further remove the dependency to the Scalalib?

If yes, I think at the very least, the commit message should mention this. Maybe wes should even put it in another PR (the first two commits are of a different character in this case).

Further, there is still a point that actually uses `js.UndefOr` (the object, not the type).

If no, I'm not quite convinced it is an improvement. While it slightly simplifies the accessor code, it makes it more implicit (especially with `decodeComponent` supporting nulls). The regex extraction code is IMO less simple. Comparison logic is a bit more readable, especially in `relativize` but if we make `cmpOpt` available there as well, I think it is acceptable.

2022-04-30 06:17 UTC, gzm0 commented on javalib/src/main/scala/java/net/URI.scala
> +  @inline private def fld(idx: Int): String = _fld(idx).orNull
This still uses `js.UndefOr`.

2022-05-02 08:27 UTC, sjrd commented
I ran into it while getting rid of the Scala library dependencies in javalib, yes. But IMO it made sense on its own. Anyway, if it's not obviously better to you, it doesn't belong in this PR, indeed. I have move that commit to a separate PR #4667.

2022-05-02 16:17 UTC, gzm0 approved these changes

2022-05-02 16:17 UTC, merged