WiP Checked behavior for NullPointerExceptions.
scala-js/scala-js pull request #4738
Opened 2022-10-02 14:41 UTC by sjrd

WiP. Needs benchmarks and a good commit message.

2022-11-09 19:51 UTC, sjrd commented
This is now ready for review. I leave it "draft" because it is based on #4750.

2022-11-15 15:47 UTC, sjrd commented
I decomposed the giant commit *a little bit*, trying to isolate changes that are not tightly integrated with the NPE checked behavior. Unfortunately, the big commit remains big.

2022-11-16 23:00 UTC, sjrd commented
I decomposed things a bit further, and even extracted two preparation PRs as #4754 and #4756.

2022-11-22 19:23 UTC, sjrd commented
Rebased.

@gzm0 Do you want to still have a look at this, or shall I create a Version commit off of `main` now?

2022-11-22 19:37 UTC, gzm0 commented
> or shall I create a Version commit off of main now?

Let's release. I'll have a look at this now, but it'll take a bit to finish :)

2022-11-22 19:51 UTC, sjrd commented
Sounds good. There we go: https://github.com/sjrd/scala-js/commit/e1ddd647edb9de2466705b2d8a3b3211132d6ca3

2022-11-25 17:25 UTC, gzm0 requested changes
Mostly nits and minor improvements. One higher level concern about usability of the AssumeNotNull tre.

2022-11-25 17:25 UTC, gzm0 commented on partest-suite/src/test/resources/scala/tools/partest/scalajs/2.13.10/run/t8601d.sem
> +nullPointers
Did you check that there are no other partests that pass with these semantics? Maybe worth doing in an additional commit.

2022-11-25 17:25 UTC, gzm0 commented on test-suite/shared/src/test/scala/org/scalajs/testsuite/compiler/NullPointersTest.scala
> +    assumeTrue("assuming compliant null pointer checks", hasCompliantNullPointers)
Annotate this with `@BeforeClass` to make it clear that the entire test assumes NPEs (you can also then remove it from the individual tests).

2022-11-25 17:25 UTC, gzm0 commented on test-suite/shared/src/test/scala/org/scalajs/testsuite/compiler/NullPointersTest.scala
> +      // charAt is a bit special
Maybe clarify that the implementation is special, not the behavior. I tripped over this.

2022-12-05 06:54 UTC, gzm0 commented
I have been thinking: Would it be completely outrageous to introduce nullability (and maybe even preciseness) into Scala.js core typesystem?

2022-12-05 09:02 UTC, sjrd commented
> I have been thinking: Would it be completely outrageous to introduce nullability (and maybe even preciseness) into Scala.js core typesystem?

That would probably be at least somewhat outrageous. :-p

The problem I see with that is that it opens up the IR for all kinds of changes that we would like to do for the sake of the optimizer only. I don't think that's a good idea, as we make the very stable definition dependent on what basically amounts to implementation details.

To be fair, we already crossed that line when we introduced *records* in the IR structure. I'm not sure I can truly call that a *mistake*, as I'm not sure how else we could have reasonably passed them from the optimizer to the emitter otherwise. Nevertheless, it is a bit of a transgression of the principle of separate responsibilities.

2022-12-05 09:23 UTC, gzm0 commented
I see the argument of not leaking implementation details. But it's not like nullability and/or null-safety is such an arcane concept (exact types feel different) or a concept never provided by compilers (IMO it is fair to open up this to compilers as well).

2022-12-05 09:34 UTC, sjrd commented
To truly open it up to compilers, we also need to provide `TypeRef`s for non-nullable classes, so that they can be used in `MethodName`s. That's quite some more effort.

If only we were going to use that in Scala 3 with strict nulls, that would be worth it. But the run-time semantics of strict nulls are still going to be erasure-based (like all other semantics in Scala), so realistically we will not be able to compile Scala-level non-nullable types to IR-level non-nullable types without putting portability at risk.

2022-12-05 16:32 UTC, sjrd commented on linker/shared/src/main/scala/org/scalajs/linker/frontend/optimizer/OptimizerCore.scala
> +            if (isStat) {
Yes, this is necessary to avoid forcing `texpr` (avoid calling `finishTransformExpr(texpr)`) when it is known to be non-null.

2022-12-05 18:55 UTC, sjrd commented on linker/shared/src/main/scala/org/scalajs/linker/frontend/optimizer/OptimizerCore.scala
> +            if (isStat) {
Hum, actually, with the changes in `keepOnlySideEffects`, this does not seem to have a real impact. I have reverted this particular diff.

2022-12-05 19:12 UTC, sjrd commented on linker/shared/src/main/scala/org/scalajs/linker/frontend/optimizer/OptimizerCore.scala
> +         * therefore pure by construction.
Indeed, the optimizer can do that for all code outside of the javalib (which must go through the static method). Doing the stupid thing does create a few more intermediate variables for calls inside the javalib, but it is negligible. I think I wrote this code before I came up with `withTempLocalDefs`, and the stupid thing actually required a lot of boilerplate. Now it's easier, so I changed it.

2022-12-05 19:23 UTC, sjrd commented on linker/shared/src/main/scala/org/scalajs/linker/frontend/optimizer/OptimizerCore.scala
> +        // This is a private API: `runtimeClass` is known not to be `null`
For `GenericArrayBuilderResult`, even with `withNewLocalDefs`, it's very annoying to deal with the null check + the evaluation order + still checking when it's a constant and extracting that. It complicates the code quite a lot, for something that is never going to be necessary. So I would rather not do that.

If we don't do it for `GenericArrayBuilderResult`, it doesn't make sense to do it for `ArrayBuilderZeroOf`.

2022-12-05 19:42 UTC, sjrd commented
I think I addressed all the comments except checking whether more partest pass with `nullPointers` (I will do that tomorrow)

For the `AssumeNotNull` problem: it is a bit a brittle, yes. But I don't really see what else to do, except duplicating all the NPE-able nodes, as you mentioned, but IMO that would be *more* brittle because of the code duplication and the potential for mistakes. The `AssumeNotNull` should be safe as long as no one intercepts and modifies the IR between the optimizer and the emitter. But that is anyway something that we don't truly support.

2022-12-05 19:42 UTC, sjrd commented on linker/shared/src/test/scala/org/scalajs/linker/OptimizerTest.scala
> +      consoleLog(Apply(EAF, receiver, cloneMethodName, Nil)(AnyType))
This is now in the commit that changes `keepOnlySideEffects`.

2022-12-06 06:37 UTC, gzm0 commented
Last question RE null tracking: Is there anything preventing is from introducing a `TransientType` analogous to the trees? We could then:
- Use this to implement records (IIRC records cannot be transient ATM because they need their own type).
- Use this for null tracking

2022-12-06 17:48 UTC, gzm0 commented
> We still need to insert AssumeNotNull nodes to actually cast trees into a something with NonNullableType.

Hmmm... If that's the case, then it's indeed pointless. My hope was that the trees we care about here have non-automatic types, so we could just re-type the trees. But indeed, now I realize that we'd need this in the receiver trees. And they are completely arbitrary :-/

2022-12-06 17:58 UTC, gzm0 approved these changes
Unless you object, I propose to go ahead with this and tackle the transient type issue if we see that AssumeNotNull is too brittle.

2022-12-06 18:16 UTC, sjrd commented
> Unless you object, I propose to go ahead with this and tackle the transient type issue if we see that AssumeNotNull is too brittle.

Sounds good. Let's do that.

2022-12-06 18:17 UTC, merged