Fix #4762: Drop Scala 2.12.1
scala-js/scala-js pull request #4764
Opened 2022-12-10 18:02 UTC by gzm0

2022-12-10 18:02 UTC, gzm0 commented
Only the last commit is part of this PR.

2022-12-11 09:16 UTC, sjrd requested changes
There's a 2.12.1-specific override in `scalalib/override-2.12.1/` that should be removed as well.

2022-12-11 09:16 UTC, sjrd commented on compiler/src/main/scala/org/scalajs/nscplugin/GenJSCode.scala
> +            !areSameFinals || (lsym == BoxedFloatClass || lsym == BoxedDoubleClass)
The sentence

> The latter case is only avoided in 2.12.2+, to remain bug-compatible with the Scala/JVM compiler.

in the comment above this code should be removed.

2022-12-11 09:41 UTC, sjrd approved these changes

2022-12-11 15:12 UTC, merged