Fix #4774: Properly track version changes in JS methods
scala-js/scala-js pull request #4775
Opened 2022-12-25 17:59 UTC by gzm0

2022-12-27 16:14 UTC, sjrd requested changes
Nits only. There's also a Scalastyle issue.

2022-12-27 16:14 UTC, sjrd commented on linker/shared/src/test/scala/org/scalajs/linker/IncrementalTest.scala
> +          )),
```suggestion
          )
      ),
```

2022-12-27 16:14 UTC, sjrd commented on linker/shared/src/test/scala/org/scalajs/linker/IncrementalTest.scala
> +                  Some(int(if (pre) 1 else 2)))(EOH.withInline(true), UNV)))
```suggestion
                  Some(int(if (pre) 1 else 2)))(EOH.withInline(true), UNV)
          )
      )
```

2022-12-27 16:14 UTC, sjrd commented on linker/shared/src/test/scala/org/scalajs/linker/IncrementalTest.scala
> +                  })))(EOH, UNV))),
Same here.

2022-12-27 16:14 UTC, sjrd commented on linker/shared/src/test/scala/org/scalajs/linker/IncrementalTest.scala
> +                  Some(int(if (pre) 1 else 2)))(EOH.withInline(true), UNV)))
Same here.

2022-12-31 14:55 UTC, gzm0 commented
Updated.

2022-12-31 15:30 UTC, sjrd approved these changes

2022-12-31 17:21 UTC, merged