Add `j.u.c.Flow`
scala-js/scala-js pull request #4792
Opened 2023-01-18 22:49 UTC by armanbilge

https://docs.oracle.com/javase/9/docs/api/java/util/concurrent/Flow.html

Since they are just interfaces, what are we looking for in terms of tests?

2023-01-19 09:06 UTC, sjrd commented
The tests we do for pure interfaces are: create instances of it, "upcast" them to the interface type, call methods. This is to make sure that the binary API of the methods declared in the interfaces are actually.correct.

See for example https://github.com/scala-js/scala-js/blob/v1.12.0/test-suite/shared/src/test/scala/org/scalajs/testsuite/javalib/util/function/LongSupplierTest.scala

2023-01-19 10:48 UTC, sjrd requested changes

2023-01-19 10:48 UTC, sjrd commented on javalib/src/main/scala/java/util/concurrent/Flow.scala
> +  trait Publisher[T] {
We do put `@FunctionalInterface` when the Java interface has it.

2023-01-19 10:48 UTC, sjrd commented on javalib/src/main/scala/java/util/concurrent/Flow.scala
> +    def subscribe(subscriber: Subscriber[T]): Unit
```suggestion
    def subscribe(subscriber: Subscriber[_ >: T]): Unit
```

2023-01-19 10:48 UTC, sjrd commented on javalib/src/main/scala/java/util/concurrent/Flow.scala
> +    def onSubscribe(subscription: Subscription): Unit
Please order the methods according the "Method Detail" section of the JavaDoc (not by alphabetical order).

2023-01-19 10:48 UTC, sjrd commented on javalib/src/main/scala/java/util/concurrent/Flow.scala
> +  }
Same here (so swap them in this case).

2023-01-20 11:54 UTC, sjrd requested changes
Looks good except for some missing braces in the tests, to adhere to our coding style.

2023-01-20 11:54 UTC, sjrd commented on test-suite/shared/src/test/require-jdk11/org/scalajs/testsuite/javalib/util/concurrent/FlowTest.scala
> +  def makeProcessor[T, R](): Flow.Processor[T, R] =
```suggestion
  def makeProcessor[T, R](): Flow.Processor[T, R] = {
```
Same for all the `makeX` methods.

According to our coding style:
https://github.com/scala-js/scala-js/blob/main/CODINGSTYLE.md#braces

2023-01-20 18:16 UTC, armanbilge commented
Oh, I forgot to add `defaultBufferSize()` 😅 

https://docs.oracle.com/javase/9/docs/api/java/util/concurrent/Flow.html#defaultBufferSize--

2023-01-20 19:03 UTC, sjrd approved these changes

2023-01-20 23:19 UTC, merged

2024-02-29 15:11 UTC, armanbilge commented
Update: thanks to this interface is now trivial for users to consume FS2 streams in Laminar/Airstream, without either library knowing about each other. I think that's really cool :)

- https://github.com/typelevel/fs2/pull/3160
- https://github.com/raquo/Airstream/pull/122