Implement ju.TreeMap
scala-js/scala-js pull request #4798
Opened 2023-01-21 19:30 UTC by gzm0

2023-01-21 19:31 UTC, gzm0 commented
Depends on #4797.

2023-01-21 19:32 UTC, gzm0 commented
@sjrd I'm not sure whether this is enough test coverage. It does re-use RedBlackTree, so we don't really need to test the core more, but probably some "minor" forwarders are untested.

2023-01-21 20:32 UTC, sjrd requested changes
The tests look good enough to me. This looks great.
I only have very minor comments.

2023-01-21 20:32 UTC, sjrd commented on javalib/src/main/scala/java/util/TreeMap.scala
> +      implicit protected val comp: Comparator[_ >: K]) extends AbstractSet[Map.Entry[K, V]] {
```suggestion
      implicit protected val comp: Comparator[_ >: K])
      extends AbstractSet[Map.Entry[K, V]] {
```

2023-01-21 20:32 UTC, sjrd commented on javalib/src/main/scala/java/util/TreeMap.scala
> +    // Common implementation of pollFirstEntry() and pollLastEntry()
Double blank line.

2023-01-21 20:33 UTC, sjrd commented
The CI says:
```
[error] C:\projects\scala-js\test-suite\shared\src\test\scala\org\scalajs\testsuite\javalib\util\TreeMapTest.scala:68:33: inferred type arguments [K,?0] do not conform to method comparing's type parameter bounds [T,U <: Comparable[_ >: U]]
[error]     val natural = ju.Comparator.comparing((_: K).asInstanceOf[Comparable[Any]])
[error]                                 ^
[error] C:\projects\scala-js\test-suite\shared\src\test\scala\org\scalajs\testsuite\javalib\util\TreeMapTest.scala:68:62: type mismatch;
[error]  found   : java.util.function.Function[K,Comparable[Any]]
[error]  required: java.util.function.Function[_ >: T, _ <: U]
[error]     val natural = ju.Comparator.comparing((_: K).asInstanceOf[Comparable[Any]])
[error]                                                              ^
[error] two errors found
[error] (testSuite2_12 / Test / compileIncremental) Compilation failed
```

2023-01-22 09:47 UTC, gzm0 commented
Rebased and addressed review comments.

2023-01-22 10:32 UTC, sjrd approved these changes

2023-01-22 10:35 UTC, sjrd commented
The following commands are failing in the CI:
```
sbt "set scalaJSLinkerConfig in testSuite.v2_12 ~= makeCompliant" testSuite2_12/test
```
On JDK 16, the JVM test suite fails:
```
sbt testSuiteJVM2_12/test testSuiteExJVM2_12/test
```

2023-01-22 12:26 UTC, gzm0 commented
Seems this is affected by: https://bugs.openjdk.org/browse/JDK-8259622?subTaskView=unresolved

2023-01-22 12:33 UTC, gzm0 commented
Updated. For ease of review, I have made two commits to be squashed.

2023-01-22 16:09 UTC, sjrd approved these changes
LGTM after squashing.

2023-01-22 21:42 UTC, merged