Fix #4783: Implement java.nio.charset.Charset.availableCharsets
scala-js/scala-js pull request #4799
Opened 2023-01-21 19:50 UTC by gzm0

2023-01-21 19:50 UTC, gzm0 commented
Depends on #4798.

2023-01-21 20:40 UTC, sjrd requested changes

2023-01-21 20:40 UTC, sjrd commented on test-suite/shared/src/test/scala/org/scalajs/testsuite/niocharset/CharsetTest.scala
> +    assertSame(US_ASCII, c.get("us-ASCII"))
Some more test ideas:
* Test the other supported ones, for completeness?
* Test that we cannot find charsets by their *aliases* this way
* Test that we cannot find any non-existing charset either
* Actually test the *listing* of all the expected charsets (in order) -- this needs to be guarded by an `!isOnJVM` or something

2023-01-22 10:42 UTC, sjrd approved these changes

2023-01-22 22:05 UTC, sjrd commented
This needs a rebase but otherwise LGTM

2023-01-23 09:02 UTC, sjrd approved these changes

2023-01-23 10:21 UTC, merged