Fix #4835: Treat excluded classes for Tagger as special hops.
scala-js/scala-js pull request #4846
Opened 2023-04-07 17:08 UTC by sjrd

Previously, we more or less abused the concept of dynamic dependencies to handle them. This was based on the observation that we "must" split modules at those boundaries. See https://github.com/scala-js/scala-js/issues/4327#issuecomment-1059984564

However, as #4835 highlights, that observation ignored one aspect of dynamic dependencies: that when A--dyn-->B, A--static-->C and B--static-->C, by the time we load `B`, we know that `C` has already been loaded, and it is therefore OK to put A and C in the same module but not B.

For the excluded classes for `SmallModulesFor`, we cannot make that assumption. On the contrary, relying on it causes a circular dependency between the A-C module and the B module.

Instead, we now handle hops into excluded classes, from non-excluded classes, as special hops that need to be tracked. In the eventual tagging scheme of a class, we include the number of hops into excluded classes that are done to reach it from a root. If several paths have different hop counts, we track all of them (in a `BitSet`).

This commit also fixes #4833.

2023-04-08 15:42 UTC, gzm0 commented
I've done another iteration over this, and it turns out I was wrong yesterday: We only really need the maximum amount of hops as a tag.

Here's a proof (with unicode, so it can be copied into the comments):

```
Given

G = (V, E), acyclic, V = F ∪ C, F ∩ C = ∅

t : V → ℕ:
  ∀ (v1, v2) ∈ E : t(v1) ≤ t(v2)
  ∀ (f, c) ∈ E : f ∈ F, c ∈ C ⇒ t(f) < t(c)

Define

G' = (V', E'), V' = F ∪ C'

C' = { n ∈ ℕ | ∃ c ∈ C : t(c) = n }

E' = { (f1, f2) ∈ E | f1, f2 ∈ F } ∪
     { (f, n) | f ∈ F, ∃ c ∈ C : (f, c) ∈ E : t(c) = n } ∪
     { (n, f) | f ∈ F, ∃ c ∈ C : (c, f) ∈ E : t(c) = n } ∪
     { (n, m) | n ≠ m, ∃ c1, c2 ∈ C : (c1, c2) ∈ E : t(c1) = n, t(c2) = m }
	 
t' : V' → ℕ:

t'(f) = t(f)  (if f ∈ F)
t'(n) = n     (if n ∈ C')

Lemma 1 (unproven)

∀ (v1, v2) ∈ E' : t'(v1) ≤ t'(v2)

Lemma 2 (unproven)

∀ (f, n) ∈ E' : f ∈ F, n ∈ C' : t'(f) < t'(n)

Lemma 3

∀ (n, m) ∈ E' : n,m ∈ C' ⇒ t'(n) < t'(m)

Follows from Lemma 1 and (n, m) ∈ E' ⇒ n ≠ m (by definition).

Theorem

G' is acyclic

Proof by contradiction.

Assume ∃ p = x1, ..., xn (x1 = xn, n > 1, xi ∈ V)

∃ xi ∈ C' by contradiction: ∀ xi ∈ F ⇒ p is a cycle in G

∃ xi ∈ F by contradiction: ∀ xi ∈ C' ⇒
  t'(xi) increases strictly monotonically (by Lemma 3),
  but x1 = xn ⇒ t'(x1) = t'(xn)
  
Therefore,

∃ (xi, xj) ∈ p : xi ∈ F, xj ∈ C'

Therefore (by Lemma 1)

t'(x1) ≤ ... ≤ t'(xi) < t'(xj) ≤ ... ≤ t'(xn) ⇒ t'(x1) < t'(xn)

But x1 = xn ⇒ t'(x1) = t'(xn), which is a contradiction.

Therefore, G' is acyclic.
```

PTAL. LMK if you think the lemmas need proving.

2023-04-08 15:45 UTC, gzm0 requested changes

2023-04-08 15:45 UTC, gzm0 commented on linker/shared/src/main/scala/org/scalajs/linker/frontend/modulesplitter/Tagger.scala
> -
Spurious removal?

2023-04-09 08:44 UTC, sjrd commented
I'm convinced by the lemmas. I could prove them in my head. I still have to work through the rest, including fully grasping how the theorem relates to the problem. I will do that tomorrow. I won't have time before then.

2023-04-09 15:08 UTC, gzm0 commented
I've taken the liberty of building on this PR to implement the single tag strategy. An explanation of how the proof relates to the problem is here:

https://github.com/scala-js/scala-js/pull/4848/files#diff-41592dd4be7fea4b2f2b47ffeac0d47b0238ae1aeb15e5504b0ad7d32fa2c3cdR71-R91

2023-04-10 10:54 UTC, sjrd commented
Superseded by #4848.

2023-04-10 10:54 UTC, closed without merging