Call-site inline single dispatch calls to JS methods
scala-js/scala-js pull request #4903
Opened 2023-09-17 13:41 UTC by gzm0

2023-09-17 13:46 UTC, gzm0 commented
Still needs a test. IIUC the best we can do (given the infrastructure we have) is test that the compiler generates an Apply node with the correct flags.

2023-09-17 14:35 UTC, sjrd reviewed
Looks good so far.

2023-09-17 14:35 UTC, sjrd commented on compiler/src/main/scala/org/scalajs/nscplugin/GenJSExports.scala
> +        if (allowCallsiteInlineSingle && overloads.size == 1) {
Maybe we should take this fast path even when `!allowCallsiteInlineSingle`, and use `inline = allowCallsiteInlineSingle` a few lines below?

2023-09-17 14:35 UTC, sjrd commented on compiler/src/main/scala/org/scalajs/nscplugin/GenJSExports.scala
> +              genApplyForSym(formalArgsRegistry, setters.head, static, inline = true)
Same here?
```suggestion
            if (setters.size == 1) {
              genApplyForSym(formalArgsRegistry, setters.head, static, inline = allowCallsiteInlineSingle)
```

2023-09-18 16:12 UTC, sjrd requested changes
One wrong-commit comment, but otherwise LGTM.

2023-09-18 16:12 UTC, sjrd commented on compiler/src/main/scala/org/scalajs/nscplugin/GenJSExports.scala
> +          ensureResultBoxed(genApplyMethod(receiver, sym, args, inline = inline), sym)
These are in the wrong commit.

2023-09-23 09:16 UTC, sjrd approved these changes

2023-09-23 10:34 UTC, merged