Allocate all emitter var field strings statically
scala-js/scala-js pull request #4911
Opened 2023-10-15 16:47 UTC by gzm0

Memory profile analysis shows ~120k duplicates of the string "$n" amounting to ~6MB waste (on the test suite).

Further digging revealed that this happens through the "$n" call-helper (null check) via:

- SJSGen#genCallHelper
- VarGen#globalVar
- VarGen#globalVarIdent
- VarGen#genericIdent

By defining the relevant strings statically (including the leading `$`), we avoid the duplication.

Discovered while working on https://github.com/scala-js/scala-js/issues/4906.

2023-10-15 16:48 UTC, gzm0 commented
Based on #4909 due to merge conflicts.

2023-10-16 08:13 UTC, sjrd requested changes
Very nice. I only have a few comments, most of them typos.

2023-10-17 18:02 UTC, gzm0 commented on linker/shared/src/main/scala/org/scalajs/linker/backend/emitter/VarFld.scala
> +private[emitter] final class VarFld private (val str: String) extends AnyVal
Only brevity. And it's true that saving 2 chars is likely not worth the additional abbreviation.

2023-10-17 18:03 UTC, gzm0 commented
I have addressed all the comments. I have also added `private[emitter]` to `object VarField`.

2023-10-18 13:11 UTC, sjrd approved these changes

2023-10-18 13:12 UTC, merged