Remove the parameters to StoreModule IR nodes.
scala-js/scala-js pull request #4943
Opened 2024-02-12 12:24 UTC by sjrd

`StoreModule` was always implicitly assumed to be used only in the constructor of the corresponding module class, and with a `This()` rhs.

We now include that assumption as a core truth of `StoreModule()`, and therefore remove its two arguments.

A deserialization hack reads they old arguments but throws them away. In theory this could change the meaning of existing IR, but nothing that would have been emitted by our compilers.

2024-02-12 17:44 UTC, sjrd commented
While doing this, I discovered that we do not, in fact, emit any `StoreModule` for JS module classes. I don't think that was specifically intended. Should we do it?

2024-02-15 12:18 UTC, gzm0 requested changes
All in all, I think this is a clear improvement.

First review pass. I'm on mobile, so I might have missed some stylistic things. Still releasing the review, because I think it can already be useful.

2024-02-15 12:18 UTC, gzm0 commented on ir/shared/src/main/scala/org/scalajs/ir/Serializers.scala
> +          }
Can we validate these assumptions? IIRC there is precedent for this kind of "deserialization validation".

I think I'd just much rather have a failure here on unexpected IR than some behavior change in the code.

2024-02-15 12:18 UTC, gzm0 commented on linker/shared/src/main/scala/org/scalajs/linker/checker/ClassDefChecker.scala
> +        if (env.thisType == NoType)
I was thrown off by this. Maybe add a comment that this (no pun intended) can happen in a JS ctor before the super call?

2024-02-15 12:18 UTC, gzm0 commented on linker/shared/src/main/scala/org/scalajs/linker/checker/ClassDefChecker.scala
Add unit test for the new checks? IIRC we wanted to test new additions to the checkers.

2024-02-15 15:11 UTC, sjrd commented
Addressed the comments.

2024-02-16 08:51 UTC, merged