Replace (Par)TrieMap with ConcurrentHashMap in IncOptimizer
scala-js/scala-js pull request #4974
Opened 2024-04-05 15:12 UTC by gzm0

- Reduces residual retained size of the IncOptimizer on the test suite
  from 166MB to 144MB.
- ~10% batch speedup on the optimizer.

2024-04-05 15:13 UTC, gzm0 commented
![plot](https://github.com/scala-js/scala-js/assets/1140323/6b7816b4-11f1-48fb-b3eb-4255cd3ad9fa)

[logger-timings.csv](https://github.com/scala-js/scala-js/files/14886851/logger-timings.csv)

2024-04-05 17:15 UTC, sjrd requested changes
Very nice :)

I only have one real comment about the tests.

2024-04-05 17:15 UTC, sjrd commented on linker/shared/src/main/scala/org/scalajs/linker/frontend/optimizer/IncOptimizer.scala
> +  private def classOrElse[T >: Class](className: ClassName, default: =>T): T = {
Coding style nit:
```suggestion
  private def classOrElse[T >: Class](className: ClassName, default: => T): T = {
```

2024-04-06 11:26 UTC, gzm0 commented on test-suite/shared/src/test/scala/org/scalajs/testsuite/javalib/util/concurrent/ConcurrentHashMapTest.scala
> +    val seen = mutable.Set.empty[(String, Int)]
Good catch.

2024-04-06 11:27 UTC, gzm0 commented
I was having second thoughts about implementing the supposedly parallel `forEach` serially unconditionally. I have added a commit (to be squashed) which disallows values of `parallelismThreshold` other than `Long.MaxValue`.

WDYT?

2024-04-06 12:04 UTC, sjrd commented
Hum I don't think that's OK. It directly goes against our policy "if it links, it's correct". Does the API *guarantee* any degree of parallelism? It didn't seem like it does when I looked at it. If it doesn't, always executing serially is correct.

2024-04-06 12:43 UTC, gzm0 commented
JavaDoc says:

> Using a value of 1 results in maximal parallelism by partitioning into enough subtasks to fully utilize the [ForkJoinPool.commonPool()](https://docs.oracle.com/javase/8/docs/api/java/util/concurrent/ForkJoinPool.html#commonPool--) that is used for all parallel computations.

So yeah, we could argue that if we ever were to implement `ForkJoinPool.commonPool`, we'd implement `ForkJoinPool.getCommonPoolParallelism` to return 1. So that in turn would mean it's OK to allow any parallelism level.

2024-04-06 12:44 UTC, gzm0 commented
I have removed the last commit again.

2024-04-06 13:17 UTC, sjrd approved these changes

2024-04-06 15:50 UTC, merged