Fix #5044: Handle the IllegalArgumentExceptions in jlr.Array.newInstance.
scala-js/scala-js pull request #5045
Opened 2024-09-21 16:45 UTC by sjrd

The case of an empty array of dimensions for the multi-dimensions overload is handled in user-space. The case of `classOf[Unit]` is handled in the backends, since not doing so leaves the door open for user-space IR to break the fundamental invariant that there is no array of `void`.

In the JS backend, we follow the strategy of int/long div/mod to emit the target method only if `IllegalArgumentException.<init>()` is reachable. In the Wasm backend, since we do not have that infrastructure, for now we add an unconditional dependency on that constructor, like we do for `jl.Class.<init>()`.

2024-09-24 17:39 UTC, gzm0 requested changes
TBH: I find the refactor confusing.

The way I think about this is that the approximation / usage happens in the CoreJSLib, not the GlobalKnowledge: Since `ArithmeticException` isn't present, we know that no division by zero can be present.

Note that the converse is not true: Just because `ArithmeticException` is present, does not necessarily mean a division by zero is present.

So I feel the refactoring actually wrongly names what the GlobalKnowledge provides (would this information come from the analysis, that would be something different of course).

I feel the existing comment in wasmemitter/Emitter actually re-inforces this way of looking at it:

```
// TODO Ideally we should not require these, but rather adapt to their absence
```

I have no comments on the second commit.

2024-09-24 17:40 UTC, gzm0 commented on linker/shared/src/main/scala/org/scalajs/linker/analyzer/Infos.scala
> +                    case _                       => builder.addUsedIntLongDivModByMaybeZero()
Just TBC: This refactoring can make sense.

2024-09-25 08:23 UTC, sjrd commented
All right, I see your point.

I downplayed the first commit. Now it is only checking the specific constructor, but otherwise the naming is unchanged.

2024-09-25 11:02 UTC, gzm0 approved these changes

2024-09-25 11:25 UTC, merged