Fix #5048: actionable error message for Wasm backend when no modules are defined
scala-js/scala-js pull request #5049
Opened 2024-09-29 03:27 UTC by tanishiking

https://github.com/scala-js/scala-js/issues/5048

After the 1.17.0 release, I received several questions about the error message: `The WebAssembly backend does not support multiple modules. Found: `. This is caused by users not exporting anything and not setting `scalaJSUseMainModuleInitializer := true`. However, for those unfamiliar with Scala.js, the current error message seems somewhat misleading.

---

The current error message in `WebAssemblyLinkerBackend` is not clear for users not very familiar with Scala.js when no modules are defined. It says: `"The WebAssembly backend does not support multiple modules. Found: "`.

https://github.com/scala-js/scala-js/blob/7c95972e30c9897440e4404515d05bf663639daa/linker/shared/src/main/scala/org/scalajs/linker/backend/WebAssemblyLinkerBackend.scala#L69-L72

This message can be confusing and doesn't provide actionable steps to resolve the issue. We may want to update the error message to clearly state the problem and provide guidance on how to fix it.

2024-09-29 03:28 UTC, tanishiking commented on linker/shared/src/main/scala/org/scalajs/linker/backend/WebAssemblyLinkerBackend.scala
> +            "2. Annotate exported functions with @JSExportTopLevel")
Is there anything we can do?

2024-09-30 11:46 UTC, sjrd requested changes
Let's add `irJS2_12/fastLinkJS` as a test in `Jenkinsfile` to make sure this works.

Regarding the commit message:

* Use `Wasm:` instead of `[Wasm]` to match what we've been using so far.
* Could you arrange the commit message so that lines fit more or less in 72 characters?

Thanks.

2024-09-30 15:47 UTC, sjrd approved these changes
Thanks.

I took the liberty to adjust the commit message a bit more, to make it more consistent with our usual commit message (notably: past tense for what was before the commit; present tense for what is after the commit).

2024-09-30 23:19 UTC, tanishiking commented
> (notably: past tense for what was before the commit; present tense for what is after the commit).

Thanks! That's clear and easy-to-understand instruction ❤️

2024-09-30 23:35 UTC, merged