Restrict usages of StoreModule even further.
scala-js/scala-js pull request #5059
Opened 2024-10-21 11:28 UTC by sjrd

Alternative to #5057. The first commit is the same as the one in #5057.

2024-11-02 12:45 UTC, gzm0 requested changes

2024-11-02 12:45 UTC, gzm0 commented on linker/shared/src/main/scala/org/scalajs/linker/checker/ClassDefChecker.scala
> +        /* If the super constructor call was inlined, the StoreModule can be anywhere.
Ah, I think this answers my question about it being implicit :)

2024-11-02 12:45 UTC, gzm0 commented on linker/shared/src/main/scala/org/scalajs/linker/checker/ClassDefChecker.scala
> -    checkBlockStats(afterSuperStoreModulesHandled, envJustAfterSuper)
As I commented on #5057, I don't think we should do this (but start emitting store module for JS modules as well).

2024-11-02 12:45 UTC, gzm0 commented on linker/shared/src/test/scala/org/scalajs/linker/checker/ClassDefCheckerTest.scala
Add a test that tests a `StoreModule` at the top level after the the super ctor call (but not immediately after) is not allowed.

2024-11-03 14:06 UTC, gzm0 approved these changes

2024-11-03 14:19 UTC, sjrd commented
Fixed scalastyle 🤦‍♂️

2024-11-03 20:08 UTC, merged